### ISSUE TITLE
Do you have stable URLs for specific materials?

### ISSUE THREAD

**Issue by danbri** [cpauloh/semmd#1]
We have a 'material' property in schema.org that takes URLs now, see https://github.com/schemaorg/schemaorg/issues/1294
- Current official version: http://schema.org/material
- Editor's draft of new version: http://webschemas.org/material

The idea is that people might point off to well known URLs for specific materials (and that those might eventually provide more structured data too). If you have stable URLs we could add some examples into schema.org along these lines.

**Comment by cpauloh** [comment]
My current focus is on materials generally used for aircraft.  I seem to recall some sort of site for information about architectural materials and will try to track that down (it used RDF). 

dBPedia?
http://dbpedia.org/page/Canvas
http://dbpedia.org/page/Leather
http://dbpedia.org/page/Knitted_fabric
